// This file was auto-generated by prisma-generator-typescript-interfaces

export type AccountType = "CHECKING" | "SAVINGS" | "CREDIT_CARD" | "CASH";

export type TransactionStatus = "CLEARED" | "PENDING" | "DUPLICATE" | "REVIEWED_OK";

export interface User {
  id: string;
  email: string;
  passwordHash: string;
  name: string;
  locale: string;
  createdAt: Date;
  updatedAt: Date;
  accounts?: Account[];
  refreshTokens?: RefreshToken[];
  auditLogs?: AuditLog[];
}

export interface RefreshToken {
  id: string;
  userId: string;
  tokenHash: string;
  familyId: string;
  usedAt: Date | null;
  expiresAt: Date;
  revokedAt: Date | null;
  createdAt: Date;
  user?: User;
}

export interface Account {
  id: string;
  userId: string;
  name: string;
  type: AccountType;
  currency: string;
  createdAt: Date;
  updatedAt: Date;
  user?: User;
  transactions?: Transaction[];
}

export interface Transaction {
  id: string;
  accountId: string;
  importBatchId: string | null;
  transactionDate: Date;
  chargeDate: Date | null;
  description: Uint8Array;
  amountAgorot: Uint8Array;
  originalAmountAgorot: Uint8Array | null;
  originalCurrency: string | null;
  category: string | null;
  cardLastFour: string | null;
  status: TransactionStatus;
  dedupeHash: string | null;
  installmentNum: number | null;
  installmentOf: number | null;
  duplicateOf: string | null;
  createdAt: Date;
  account?: Account;
  importBatch?: ImportBatch | null;
  recurringMatch?: RecurringMatch | null;
  originalTransaction?: Transaction | null;
  duplicates?: Transaction[];
}

export interface ImportBatch {
  id: string;
  accountId: string;
  filename: string;
  fileHash: string | null;
  rowCount: number;
  importedAt: Date;
  transactions?: Transaction[];
}

export interface RecurringExpense {
  id: string;
  userId: string;
  name: string;
  expectedAmountAgorot: Uint8Array;
  dayOfMonth: number | null;
  matchPattern: string;
  active: boolean;
  createdAt: Date;
  updatedAt: Date;
  matches?: RecurringMatch[];
}

export interface RecurringMatch {
  id: string;
  recurringExpenseId: string;
  transactionId: string;
  month: number;
  year: number;
  matchedAt: Date;
  recurringExpense?: RecurringExpense;
  transaction?: Transaction;
}

export interface AuditLog {
  id: string;
  userId: string;
  action: string;
  tableName: string;
  recordId: string;
  oldValues: JsonValue | null;
  newValues: JsonValue | null;
  createdAt: Date;
  user?: User;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
